---
- name: Build inventory
  ansible.builtin.import_playbook: post_infra.yml

- name: Destroy workload(s)
  hosts: ocp_bastions
  become: false
  gather_facts: false
  tasks:
  - name: Fail
    ansible.builtin.fail:
      msg: This is not working as designed. Needs to implement start/stop

  - name: Fail if no action defined
    when: ACTION is not defined or ACTION == ''
    ansible.builtin.fail:
      msg: ACTION must be defined

  - name: Set facts for OpenShift cluster(s)
    ansible.builtin.include_tasks: set_cluster_facts.yml

  - name: Run Workloads to perform {{ ACTION }}
    vars:
      ACTION: destroy
    ansible.builtin.include_tasks: run_workload_on_clusters.yml
    loop: "{{ cluster_workloads }}"
    loop_control:
      loop_var: __workload
      label: "{{ __workload.name }}"
